Repository rlennon/mscplacprj2021, pull requests merged in 2021-06, with the labels that each got.

#14 Develop
  README.md
  docs/branching.md
  docs/container_registry.md
  docs/definitionOfDone.md
  docs/definitionOfReady.md
  docs/security.md
Labels: GiHub, documentation

#18 Update definitionOfReady.md
  docs/definitionOfReady.md
Labels: documentation

#17 Update definitionOfDone.md
  docs/definitionOfDone.md
Labels: documentation

#28 Create Dockerfile
  Dockerfile
Labels: build, enhancement, pipeline

#26 Create dockerization document
  docs/dockerisation.md
Labels: documentation

#27 Update and rename workflow.yml to docker-image.yml
  .github/workflows/docker-image.yml
  .github/workflows/workflow.yml
Labels: deploy, pipeline, workflow

#29 feature-basic-java-app
  pom.xml
  src/main/java/com/mscprojplac/App.java
  src/main/java/com/mscprojplac/Calculator.java
  src/test/java/com/mscprojplac/AppTest.java
Labels: app

#36 Update Dockerfile
  Dockerfile
Labels: bug

#37 Update pom.xml
  pom.xml
Labels: bug
